name: test-released-action
on:
    push:
        branches:
            - main
jobs:
    test-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: hello world 9999 action
              uses: pnminh/first-github-action@v1